Generalize submitter, .env, and bash and slurm scripts
Imageomics/distributed-downloader pull request #3
Opened 2024-05-22 21:44 UTC by egrace479

The sample `.env` file now defines paths previously defined in the submitted script. It also has the project name, so that and all the distribution of work settings can be passed to the `slurm` scripts directly through the bash coordination script (`example_scripts/submit_mpi_download.sh`) instead of needing to be redefined at the top of each file. This does add a slightly higher resource request for the verifier, but (following our group discussion) this shouldn't add much to resource allocation since it is only run for a couple seconds on each batch.

`src/submitter.py` is now the primary user interface with the package (following pre-processing steps). Its only input is the path to the `.env` file, so that it can fetch the required paths. There was also some restructuring to avoid redefining variables.

2024-05-23 13:26 UTC, thompsonmj requested changes
Only suggestion affecting function is to source the dotenv file in the bash script.

2024-05-23 13:26 UTC, thompsonmj commented on src/submitter.py
>  RECHECK = False
It won't let me comment on the line above for some reason, but `NUM_DOWNLOADERS` should also go into `hpc.env` to be configurable.

2024-05-23 13:26 UTC, thompsonmj commented on example_scripts/submit_mpi_download.sh
Need `source "${REPO_ROOT}/config/hpc.env"` under `REPO_ROOT=` now that we're specifying `DOWNLOADER_MAX_NODES`, etc. in there.

2024-05-23 13:26 UTC, thompsonmj commented on example_scripts/submit_mpi_download.sh
> +    sbatch --output="${LOGS_DIR}/${base_filename}.out" --error="${LOGS_DIR}/${base_filename}.err" --dependency=afterany:"${dependency}" "${script}" "${schedule}" "${iteration_number}" "$5" --nodes="$
```suggestion
    sbatch \
        --output="${LOGS_DIR}/${base_filename}.out" \
        --error="${LOGS_DIR}/${base_filename}.err" \
        --dependency=afterany:"${dependency}" \
        "${script}" "${schedule}" "${iteration_number}" "$5" \
        --nodes="${DOWNLOADER_MAX_NODES}" \
        --ntasks-per-node="${DOWNLOADER_WORKERS_PER_NODE}" \
        --cpus-per-task="${DOWNLOADER_CPU_PER_TASK}" \
        --account="${ACCOUNT}"
```

2024-05-23 13:26 UTC, thompsonmj commented on example_scripts/submit_mpi_download.sh
> +    sbatch --output="${LOGS_DIR}/${base_filename}.out" --error="${LOGS_DIR}/${base_filename}.err" --dependency=afterany:"${dependency}" "${script}" "${schedule}" "${iteration_number}" "$5" --nodes="$
To help readability.

2024-05-23 13:26 UTC, thompsonmj commented on example_scripts/submit_mpi_download.sh
> +    sbatch --output="${LOGS_DIR}/${base_filename}.out" --error="${LOGS_DIR}/${base_filename}.err" "${script}" "${schedule}" "${iteration_number}" "$4" --nodes="${DOWNLOADER_MAX_NODES}" --ntasks-per-n
```suggestion
    sbatch \
        --output="${LOGS_DIR}/${base_filename}.out" \
        --error="${LOGS_DIR}/${base_filename}.err" \
        "${script}" "${schedule}" "${iteration_number}" "$4" \
        --nodes="${DOWNLOADER_MAX_NODES}" \
        --ntasks-per-node="${DOWNLOADER_WORKERS_PER_NODE}" \
        --cpus-per-task="${DOWNLOADER_CPU_PER_TASK}" \
        --account="${ACCOUNT}"
```

2024-05-23 21:37 UTC, egrace479 commented
There are still some questions to be answered on overall package and things to do after this update is settled:
 1. Presumably we will want to change `mpi_downloader` to `distributed_downloader` in `src`. We then have to decide how to work with the other scripts outside of it but still in `src`. The idea is that `src/submitter.py` will be the interface that runs the whole download, while the `scripts/` and `config/` files will be modified by users to pass into the process.
 2. The resize functions should be moved out to a `tools` folder or similar at the root level of the repository. I'm fine with leaving them not generalized for now, but good to include the tools.
 3. The functioning of the preprocessing steps should be clarified (i.e., how to run `server_prep` and `MPI_download_prep`--what goes in and what actually comes out). 
 4. Similarly to 3, we need to clarify requirements for the actual download process (if nothing else, this could be the structure established by the scripts noted in 3).
 5. We need tests. In particular, this restructuring should be tested to ensure it still functions as expected.

2024-05-24 05:33 UTC, Andrey170170 approved these changes

2024-05-24 15:06 UTC, thompsonmj approved these changes
2x `osc.env` -> `hpc.env`, but I think it looks alright otherwise. Will be helpful to start getting tests written.

2024-05-24 15:06 UTC, thompsonmj commented on scripts/server_downloading_prep.slurm
>  source "${REPO_ROOT}/config/osc.env"
```suggestion
source "${REPO_ROOT}/config/hpc.env"
```

2024-05-24 15:06 UTC, thompsonmj commented on scripts/server_profiling.slurm
>  source "${REPO_ROOT}/config/osc.env"
```suggestion
source "${REPO_ROOT}/config/hpc.env"
```

2024-05-24 15:18 UTC, merged