Initial code transfer of the Downloader
Imageomics/distributed-downloader pull request #4
Opened 2024-05-28 17:37 UTC by Andrey170170

Transferred the Downloader code and made generalizing adjustments to it.

2024-05-28 19:07 UTC, egrace479 requested changes

2024-05-28 19:07 UTC, egrace479 commented on src/server_prep.py
> +    parser.add_argument('path', metavar='path', type=str, help='the path to the tsv file')
What is the tsv fle? Could you make this a little more descriptive/clear? Ex: path to the file specifying the collection of images to be downloaded, such as the GBIF multimedia.csv.

2024-05-28 19:07 UTC, egrace479 commented on src/server_prep.py
> +    parser.add_argument('output_path', metavar='output_path', type=str, help='the path to the output folder')
```suggestion
    parser.add_argument('output_path', metavar='output_path', type=str, help='the path to the output folder (folder for download components (e.g., server batches and image folder))')
```
Folder containing image folder and all the other download components (called in the MPI `py` files in `src` is the output folder, right?

2024-05-28 19:07 UTC, egrace479 commented on README.md
> +`distributed-downloader` utilizes multiple nodes on a High Performance Computing (HPC) system (specifically, an HPC with `slurm` workload manager) to download a collection of images specified in a gi
```suggestion
`distributed-downloader` utilizes multiple nodes on a High Performance Computing (HPC) system (specifically, an HPC with `slurm` workload manager) to download a collection of images specified in a given `csv`, `tsv`, or `txt` file. There are three manual steps to get the downloader running as designed; the first two function as a preprocessing step (to be done once with the initial file), and the third initiates the download (this step may be run multiple times for pre-established periods and each will pick up where the last left off).
```

2024-05-28 19:09 UTC, egrace479 commented
Note that some of the early comments there are just changing the way things are explained to try to improve clarity (including parts I wrote).

2024-05-28 19:15 UTC, thompsonmj commented on scripts/server_downloading_prep.slurm
> +#SBATCH --account=pas2136
Yes, it'd need another bash script (e.g. something like `submit_server_downloading_prep.sh`) to submit this Slurm job with parameterized account info.
I think parameterizing preprocessing scripts like this could be added as another issue.

2024-05-28 19:20 UTC, Andrey170170 commented on src/mpi_downloader/ProfilerWriter.py
> +            resized_image = cv2.resize(original_image, (1024, 1024), interpolation=cv2.INTER_LINEAR)
Currently, it is not used, it is a writer for server profiler. The whole profiler thing needs to be updated.

2024-05-28 19:22 UTC, Andrey170170 commented on src/server_prep.py
> +    parser.add_argument('path', metavar='path', type=str, help='the path to the tsv file')
Oh, sorry, I think I just forgot to change it when I copied it from a different script

2024-05-28 20:48 UTC, egrace479 commented on src/mpi_downloader/ProfilerWriter.py
> +            resized_image = cv2.resize(original_image, (1024, 1024), interpolation=cv2.INTER_LINEAR)
We should have an issue to address this.

2024-05-28 21:10 UTC, egrace479 commented
I set up the issues and added them all to a [new project](https://github.com/orgs/Imageomics/projects/46/views/1) linked to the repo. Also, set up a milestone for the package to track the timing for these things.

2024-05-29 16:42 UTC, thompsonmj approved these changes

2024-05-29 16:54 UTC, egrace479 requested changes

2024-05-29 16:54 UTC, egrace479 commented on src/submitter.py
> +    Also, paths to slurm scripts and bash a python-slurm coordination script.
```suggestion
    Also, paths to slurm scripts and a bash python-slurm coordination script.
```

2024-05-29 16:54 UTC, egrace479 commented on src/server_prep.py
> +    parser.add_argument('input_path', metavar='input_path', type=str, help='the path to the file with multimedia data, can be either a TSV file or a TXT file')
```suggestion
    parser.add_argument('input_path', metavar='input_path', type=str, help='the path to the file with multimedia data, must be a tab-delimited text file')
```

2024-05-29 16:56 UTC, egrace479 approved these changes

2024-05-29 16:56 UTC, merged